# Generated by Django 5.2.1 on 2025-06-03 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='S'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(null=True, to='home.tag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('U', 'UNISEX')], default='U'),
        ),
    ]
