# Generated by Django 5.2.1 on 2025-06-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_tags_tag_product_colors_product_img_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='code',
            field=models.CharField(default='tshirt', max_length=15),
        ),
    ]
