# Generated by Django 5.2.1 on 2025-06-03 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_designer_alter_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.designer'),
        ),
    ]
