# Generated by Django 5.2.1 on 2025-06-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_id',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
