# Generated by Django 5.2.1 on 2025-06-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_item',
            old_name='product',
            new_name='product_id',
        ),
    ]
