# Generated by Django 5.2.1 on 2025-06-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_product_cart_item_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_item',
            old_name='product_id',
            new_name='product',
        ),
    ]
