# Generated by Django 5.2.1 on 2025-06-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_product_id_cart_item_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='quan',
        ),
    ]
